---

- name: check /etc/ssh/moduli
  script: 'check-moduli.sh {{ ssh_modulus_min }}'
  when: ssh_modulus_min is defined
  register: ssh_moduli_check
  check_mode: no
  changed_when: >-
    (ssh_moduli_check.stdout | int) > 0
  tags:
    - ssh-sshd-config
    - ssh-moduli

- name: remove small moduli from /etc/ssh/moduli
  script: 'mod-moduli.sh {{ ssh_modulus_min }}'
  when: >-
    not ansible_check_mode and
    ssh_modulus_min is defined and
    ssh_moduli_check.changed
  register: ssh_moduli_configured
  changed_when: >-
    ssh_moduli_configured.stdout.find('XXXchangedXXX') != -1
  notify:
    - reload SSH daemon
  tags:
    - ssh-sshd-config
    - ssh-moduli

...
